//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
  
    ViewBag.Title = "Giỏ hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
    decimal totalAmount = Model.Sum(item => item.LineTotal);


#line default
#line hidden

#line 3 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
            if (Model.Count == 0)
            {
                

#line default
#line hidden

#line 4 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
               __o = Html.ActionLink("Tiếp tục mua hàng", "LongChauClone", "TrangChu", null, new { @class = "cta-shopping" });


#line default
#line hidden

#line 5 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                      
            }
            else
            {
                

#line default
#line hidden

#line 6 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                    foreach (var item in Model)
                    {
                        

#line default
#line hidden

#line 7 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                                             __o = item.ProductId;


#line default
#line hidden

#line 8 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                  __o = item.ProductImage ?? "/hinh/default-product.png";


#line default
#line hidden

#line 9 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                                                                           __o = item.ProductName;


#line default
#line hidden

#line 10 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                           __o = item.ProductName;


#line default
#line hidden

#line 11 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                                                                         __o = item.ProductId;


#line default
#line hidden

#line 12 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                                               __o = item.ProductId;


#line default
#line hidden

#line 13 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                                                                __o = item.Quantity;


#line default
#line hidden

#line 14 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                                                                         __o = item.ProductId;


#line default
#line hidden

#line 15 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                            using (Html.BeginForm("RemoveFromCart", "GioHang", FormMethod.Post, new { @class = "cart-remove-form" }))
                            {
                                

#line default
#line hidden

#line 16 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                           __o = Html.Hidden("productId", item.ProductId);


#line default
#line hidden

#line 17 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                                                         
                                

#line default
#line hidden

#line 18 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                                                                                          
                            }

#line default
#line hidden

#line 19 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                              
                    }

#line default
#line hidden

#line 20 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                      
            }

#line default
#line hidden

#line 21 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                       __o = totalAmount.ToString("N0");


#line default
#line hidden

#line 22 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
            using (Html.BeginForm("ApplyDiscount", "GioHang", FormMethod.Post, new { id = "discount-form" }))
            {
                

#line default
#line hidden

#line 23 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHa       "
                       __o = Html.TextBox("couponCode", null, new { placeholder = "Nhập mã giảm giá" });


#line default
#line hidden

#line 24 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHa                                        
            }

#line default
#line hidden

#line 25 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                    __o = totalAmount.ToString("N0");


#line default
#line hidden

#line 26 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
            if (Model.Count > 0)
            {
                if (User.IsInRole("Customer"))
                {
                    

#line default
#line hidden

#line 27 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
               __o = Html.ActionLink("Thanh toán", "Index", "Checkout", null, new { @class = "checkout-btn", style = "text-decoration:none;" });


#line default
#line hidden

#line 28 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                                                                                                                               
                }
                else
                {
                    

#line default
#line hidden

#line 29 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
               __o = Html.ActionLink("Đăng nhập/Đăng kí để thanh toán", "Login", "TrangChu", null, new { @class = "checkout-btn", style = "text-decoration:none;" });


#line default
#line hidden

#line 30 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                                                                                                                                                    
                }
            }
            else
            {
                

#line default
#line hidden

#line 31 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
                                                                                                                              
            }

#line default
#line hidden
DefineSection("scripts", () => {


#line 32 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\GioHang\Index.cshtml"
               __o = Url.Action("UpdateCart", "GioHang");


#line default
#line hidden
});

}
}
}
