//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Header_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Header_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\ECC20D51A9D897637962382EC9F4388934DE\2\frontend321\frontend\Views\Shared\_Header.cshtml"
                __o = Url.Action("LongChauClone", "TrangChu");


#line default
#line hidden

#line 2 "C:\Users\phamm\AppData\Local\Temp\ECC20D51A9D897637962382EC9F4388934DE\2\frontend321\frontend\Views\Shared\_Header.cshtml"
              
                var currentQuery = "";
                try
                {
                    var httpReq = ViewContext?.HttpContext?.Request;
                    if (httpReq?.QueryString != null)
                    {
                        currentQuery = httpReq.QueryString["q"] ?? "";
                    }
                }
                catch
                {
                    currentQuery = "";
                }
            

#line default
#line hidden

#line 3 "C:\Users\phamm\AppData\Local\Temp\ECC20D51A9D897637962382EC9F4388934DE\2\frontend321\frontend\Views\Shared\_Header.cshtml"
                                  __o = Url.Action("Index","Search");


#line default
#line hidden

#line 4 "C:\Users\phamm\AppData\Local\Temp\ECC20D51A9D897637962382EC9F4388934DE\2\frontend321\frontend\Views\Shared\_Header.cshtml"
                                                                                                               __o = currentQuery;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Header_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Header_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\D52A4D2A6911F019BDA781F72EE3638BE97F\4\frontend123\frontend\Views\Shared\_Header.cshtml"
                __o = Url.Action("LongChauClone", "TrangChu");


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Header_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Header_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\D52A4D2A6911F019BDA781F72EE3638BE97F\2\frontend123\frontend\Views\Shared\_Header.cshtml"
                __o = Url.Action("LongChauClone", "TrangChu");


#line default
#line hidden
}
}
}
