//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_KhauTrang_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_KhauTrang_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\7EAA9A5801D9B2A3D6994DE9245219E71AEE\2\frontend321\frontend\Views\TrangChu\KhauTrang.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";



#line default
#line hidden

#line 2 "C:\Users\phamm\AppData\Local\Temp\7EAA9A5801D9B2A3D6994DE9245219E71AEE\2\frontend321\frontend\Views\TrangChu\KhauTrang.cshtml"
          



#line default
#line hidden

#line 3 "C:\Users\phamm\AppData\Local\Temp\7EAA9A5801D9B2A3D6994DE9245219E71AEE\2\frontend321\frontend\Views\TrangChu\KhauTrang.cshtml"
          





#line default
#line hidden
}
}
}
