//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Login_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Login_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\frontend123\frontend\Views\TrangChu\Login.cshtml"
  
123\frontend\Views\TrangChu\Login.cshtml"
  
    ViewBag.Title = "Login";
    La
#line 2 "C:\Users\phamm
#line 2 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\frontend123\frontend\Views\TrangChu\Login.cshtml"
   __o = Html.Partial("_Header");


#line default
#line hidden
fault
#line hidden
l("_Header");


#line default
#line hidden
default
#line hidden
default
#line hidden
in1.cshtml";


#line default
#line hidden
}
}
}
