//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LongChauClone_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LongChauClone_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
  
    ViewBag.Title = "Long Châu Clone";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
   Html.RenderAction("CategoryNavigation", "TrangChu"); 

#line default
#line hidden

#line 4 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
        foreach (var product in Model)
        {
            var image = product.ProductImages.FirstOrDefault(img => img.IsPrimary);

            // If no image is marked "Primary", just get the first one in the list
            if (image == null)
            {
                image = product.ProductImages.FirstOrDefault();
            }

            // If the product has an image, use its URL.
            // Otherwise, use a placeholder.
            string imageUrl = (image != null) ? image.Url : "~/hinh/VitaminC.jpg";
            

#line default
#line hidden

#line 5 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
                                         
            //slug product
        

#line default
#line hidden

#line 6 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
                __o = Url.Action("ViewProduct", "TrangChu", new { slug = product.Slug });


#line default
#line hidden

#line 7 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
                         __o = Url.Content(imageUrl);


#line default
#line hidden

#line 8 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
                                                      __o = product.Name;


#line default
#line hidden

#line 9 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
           __o = product.Name;


#line default
#line hidden

#line 10 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
                         __o = product.Price.HasValue ? product.Price.Value.ToString("N0") + "đ" : "Contact us";


#line default
#line hidden

#line 11 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
            using (Html.BeginForm("AddToCart", "GioHang", FormMethod.Post))
            {
                

#line default
#line hidden

#line 12 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
                                       
                

#line default
#line hidden

#line 13 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
           __o = Html.Hidden("productId", product.Id);


#line default
#line hidden

#line 14 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
                                                     

                

#line default
#line hidden

#line 15 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
                                                                        
                

#line default
#line hidden

#line 16 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
           __o = Html.Hidden("quantity", 1);


#line default
#line hidden

#line 17 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
                                           

                

#line default
#line hidden

#line 18 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
                         
            }

#line default
#line hidden

#line 19 "C:\Users\ADMIN\AppData\Local\Temp\25E6B86A718FA8F4CF60BFE2C179E3F73335\3\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
              
        }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LongChauClone_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_LongChauClone_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\7EAA9A5801D9B2A3D6994DE9245219E71AEE\2\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
  
    ViewBag.Title = "Long Châu Clone";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LongChauClone_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_LongChauClone_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\ECC20D51A9D897637962382EC9F4388934DE\2\frontend321\frontend\Views\TrangChu\LongChauClone.cshtml"
  
    ViewBag.Title = "Long Châu Clone";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LongChauClone_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_LongChauClone_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\frontend123\frontend\Views\TrangChu\LongChauClone.cshtml"
  
    ViewBag.Title = "Long Châu Clone";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LongChauClone_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_LongChauClone_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\BA33988CE5ADB9DD20DE6936BCA27B00942E\3\frontend123\frontend\Views\TrangChu\LongChauClone.cshtml"
  
    ViewBag.Title = "Long Châu Clone";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LongChauClone_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_LongChauClone_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\BA33988CE5ADB9DD20DE6936BCA27B00942E\2\frontend123\frontend\Views\TrangChu\LongChauClone.cshtml"
  
    ViewBag.Title = "Long Châu Clone";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden
u");


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LongChauClone_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LongChauClone_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\DF82E6600C069B2C9BAF72C44952759C98B6\2\frontend123\frontend\Views\TrangChu\LongChauClone.cshtml"
  
    ViewBag.Title = "Long Châu Clone";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 2 "C:\Users\phamm\AppData\Local\Temp\DF82E6600C069B2C9BAF72C44952759C98B6\2\frontend123\frontend\Views\TrangChu\LongChauClone.cshtml"
                __o = Url.Action("LongChauClone", "TrangChu");


#line default
#line hidden
}
}
}
