//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Omega3_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Omega3_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\frontend123\frontend\Views\TrangChu\Omega3.cshtml"
  
    ViewBag.Title = "Omega3";
    Layout = "~/Views/SanPhamNoiBat/Omega3.cshtml";


#line default
#line hidden

#line 2 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\frontend123\frontend\Views\TrangChu\Omega3.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";
    var productName = "Viên uống Omega-3 Orihiro";
    var brand = "Orihiro";
    var price = 265000;
    var originalPrice = 310000;
    var rating = 4.8;
    var reviews = 102;
    var description = "Omega-3 Orihiro giúp hỗ trợ tim mạch, cải thiện trí nhớ, giảm mỡ máu và tăng cường sức khỏe não bộ.";
    var ingredients = "Dầu cá tinh khiết, EPA, DHA, Vitamin E";
    var usage = "Uống 2 viên mỗi ngày sau bữa ăn.";
    var origin = "Nhật Bản";
    var packaging = "Túi 180 viên dùng trong 90 ngày";


#line default
#line hidden

#line 3 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\frontend123\frontend\Views\TrangChu\Omega3.cshtml"
      __o = productName;


#line default
#line hidden

#line 4 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\frontend123\frontend\Views\                         tial("Html.Partial("_Header")      __o = productName;


#line default
#line hidden

#line 5 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\fron                                                                 a3.cshtml"
           __o = productName;


#line default
#line hidden

#line 6 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\fron                                    oductNproductName            __o = brand;


#line default
#line hidden

#line 7 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\fron                                                                      )     brand = price.ToString("N0");


#line default
#line hidden

#line 8 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\fron                                                          __o = price.ToString("N0");


#line default
#line hidden

#line 9 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\frontend123\frontend\Views\TrangChu\Omega3.cshtml"
               originalPrice            __o = price.ToString("N0");


#line default
#line hidden

#line 9 10C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\frontend123\frontend\Views\Tr             ega3.crating              __o = originalPrice.ToString("N0");


#line defaul1011#line hidden

#line 9 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\fron                             end\VireviewsangChu\Omega3.cshtml"
             __o = rating;


#line defaul1112line hidden

#line 10 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\fron                              hu\Omedescriptiontml"
                             __o = reviews;


#line defaul1213line hidden

#line 11 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\fron                                                        u\Omegingredients
                              __o = description;


#line defaul1314line hidden

#line 12 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\fron                                                             usage                               __o = ingredients;


#line defaul1415line hidden

#line 13 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\fron                                                           origin                                     __o = usage;


#line defaul1516line hidden

#line 14 "C:\Users\phamm\AppData\Local\Temp\9CF5FA0654132C4B8F544B5D0F800C42843C\4\frontend123\frontend\Views\TrangChu\Omega3.cshtml"
                                                      __o = packaging;


#line default
#line hidden
}
}
}
