//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_TrangChuIndex_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_TrangChuIndex_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\4DA5A4417944CF66BF3D4EA0897DCB2A1833\4\frontend\frontend\Views\TrangChu\TrangChuIndex.cshtml"
  
    ViewBag.Title = "Trang ch?";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 2 "C:\Users\phamm\AppData\Local\Temp\4DA5A4417944CF66BF3D4EA0897DCB2A1833\4\frontend\frontend\Views\TrangChu\TrangChuIndex.cshtml"
                __o = Url.Action("Index", "TrangChu");


#line default
#line hidden

#line 3 "C:\Users\phamm\AppData\Local\Temp\4DA5A4417944CF66BF3D4EA0897DCB2A1833\4\frontend\frontend\Views\TrangChu\TrangChuIndex.cshtml"
                __o = Url.Action("Login", "Account");


#line default
#line hidden

#line 4 "C:\Users\phamm\AppData\Local\Temp\4DA5A4417944CF66BF3D4EA0897DCB2A1833\4\frontend\frontend\Views\TrangChu\TrangChuIndex.cshtml"
                    __o = Url.Action("Index", "TrangChu");


#line default
#line hidden

#line 5 "C:\Users\phamm\AppData\Local\Temp\4DA5A4417944CF66BF3D4EA0897DCB2A1833\4\frontend\frontend\Views\TrangChu\TrangChuIndex.cshtml"
                            __o = Url.Action("Vitamin", "Category");


#line default
#line hidden

#line 6 "C:\Users\phamm\AppData\Local\Temp\4DA5A4417944CF66BF3D4EA0897DCB2A1833\4\frontend\frontend\Views\TrangChu\TrangChuIndex.cshtml"
                            __o = Url.Action("ThuocKeDon", "Category");


#line default
#line hidden

#line 7 "C:\Users\phamm\AppData\Local\Temp\4DA5A4417944CF66BF3D4EA0897DCB2A1833\4\frontend\frontend\Views\TrangChu\TrangChuIndex.cshtml"
                            __o = Url.Action("ThucPhamChucNang", "Category");


#line default
#line hidden

#line 8 "C:\Users\phamm\AppData\Local\Temp\4DA5A4417944CF66BF3D4EA0897DCB2A1833\4\frontend\frontend\Views\TrangChu\TrangChuIndex.cshtml"
                            __o = Url.Action("SucKhoe", "News");


#line default
#line hidden

#line 9 "C:\Users\phamm\AppData\Local\Temp\4DA5A4417944CF66BF3D4EA0897DCB2A1833\4\frontend\frontend\Views\TrangChu\TrangChuIndex.cshtml"
                            __o = Url.Action("KhuyenMai", "News");


#line default
#line hidden

#line 10 "C:\Users\phamm\AppData\Local\Temp\4DA5A4417944CF66BF3D4EA0897DCB2A1833\4\frontend\frontend\Views\TrangChu\TrangChuIndex.cshtml"
                            __o = Url.Action("ThongBao", "News");


#line default
#line hidden

#line 11 "C:\Users\phamm\AppData\Local\Temp\4DA5A4417944CF66BF3D4EA0897DCB2A1833\4\frontend\frontend\Views\TrangChu\TrangChuIndex.cshtml"
                    __o = Url.Action("Cart", "Shopping");


#line default
#line hidden
}
}
}
