//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_CoenzymeQ10_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_CoenzymeQ10_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\phamm\AppData\Local\Temp\BA33988CE5ADB9DD20DE6936BCA27B00942E\2\frontend123\frontend\Views\SanPham\CoenzymeQ10.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\phamm\AppData\Local\Temp\BA33988CE5ADB9DD20DE6936BCA27B00942E\2\frontend123\frontend\Views\SanPham\CoenzymeQ10.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
